"""Remove is_authenticated column from users table

Revision ID: 00dd006d59d1
Revises: d060f5ec3a65
Create Date: 2025-06-30 15:57:29.742044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dd006d59d1'
down_revision = 'd060f5ec3a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
