"""Add sender_name to Email model

Revision ID: 8c7139353e77
Revises: f0069ced1d62
Create Date: 2025-07-04 23:28:24.317310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7139353e77'
down_revision = 'f0069ced1d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
