"""Rename email_aliases table to email_alias

Revision ID: ab1636c64c6b
Revises: f953ed34534e
Create Date: 2025-07-01 22:15:53.518019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab1636c64c6b'
down_revision = 'f953ed34534e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_title', sa.String(length=120), nullable=False),
    sa.Column('alias_random', sa.String(length=120), nullable=False),
    sa.Column('alias_domain', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('forwarding_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('email_aliases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias_domain', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('forwarding_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias_title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('alias_random', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('email_aliases_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_aliases_pkey'))
    )
    op.drop_table('email_alias')
    # ### end Alembic commands ###
