"""Add body_html and raw columns to email

Revision ID: bd071932b8e2
Revises: 8c7139353e77
Create Date: 2025-07-05 11:34:50.652349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd071932b8e2'
down_revision = '8c7139353e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw', sa.Text(), nullable=True))
        batch_op.alter_column('alias_used',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('alias_used',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('raw')
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
