"""add flask-login fields user model

Revision ID: d060f5ec3a65
Revises: 
Create Date: 2025-06-29 21:58:08.508559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd060f5ec3a65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_prefix', sa.String(length=120), nullable=False),
    sa.Column('alias_domain', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('forwarding_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_used', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('alias_used')

    op.drop_table('email_aliases')
    # ### end Alembic commands ###
