"""forwarding email optional

Revision ID: f0069ced1d62
Revises: ab1636c64c6b
Create Date: 2025-07-04 21:13:59.167737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0069ced1d62'
down_revision = 'ab1636c64c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_alias', schema=None) as batch_op:
        batch_op.alter_column('forwarding_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_alias', schema=None) as batch_op:
        batch_op.alter_column('forwarding_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
