"""updating alias properties

Revision ID: f953ed34534e
Revises: 00dd006d59d1
Create Date: 2025-07-01 15:26:10.108672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f953ed34534e'
down_revision = '00dd006d59d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('alias_random', sa.String(length=120), nullable=False))
        batch_op.drop_column('alias_prefix')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_prefix', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('alias_random')
        batch_op.drop_column('alias_title')

    # ### end Alembic commands ###
